create database recruiter;
use recruiter;
CREATE TABLE skills (
    skill VARCHAR(100) NOT NULL UNIQUE
);

INSERT INTO skills (skill) VALUES
('artificial intelligence'),
('ai/ml'),
('machine learning'),
('deep learning'),
('natural language processing'),
('nlp'),
('computer vision'),
('data science'),
('data analysis'),
('data visualization'),
('data mining'),
('data cleaning'),
('data processing'),
('data engineering'),
('big data'),
('statistical analysis'),
('predictive modeling'),
('feature engineering'),
('model training'),
('model evaluation'),
('model deployment'),
('classification'),
('regression'),
('clustering'),
('time series analysis'),
('anomaly detection'),
('recommendation systems'),
('reinforcement learning'),
('generative ai'),
('large language models'),
('llm'),
('prompt engineering'),
('software development'),
('software engineering'),
('web development'),
('frontend development'),
('backend development'),
('full stack development'),
('mobile development'),
('api development'),
('database management'),
('object oriented programming'),
('algorithm design'),
('data structures'),
('problem solving'),
('debugging'),
('software testing'),
('unit testing'),
('integration testing'),
('test automation'),
('code review'),
('version control'),
('system design'),
('cybersecurity'),
('network security'),
('ethical hacking'),
('penetration testing'),
('cryptography'),
('threat detection'),
('vulnerability assessment'),
('security analysis'),
('digital forensics'),
('cloud computing'),
('cloud architecture'),
('cloud security'),
('devops'),
('ci/cd'),
('containerization'),
('system administration'),
('network administration'),
('business intelligence'),
('etl'),
('data modeling'),
('database design'),
('embedded systems'),
('internet of things'),
('iot'),
('robotics'),
('automation'),
('image processing'),
('signal processing'),
('ui design'),
('ux design'),
('software architecture'),
('distributed systems'),
('project management'),
('agile development'),
('scrum');


CREATE TABLE technologies (
    technology VARCHAR(100) NOT NULL UNIQUE
);

INSERT INTO technologies (technology) VALUES
('tensorflow'),
('pytorch'),
('keras'),
('scikit-learn'),
('opencv'),
('hugging face'),
('transformers'),
('cuda'),
('jupyter'),
('mlflow'),
('kubeflow'),
('onnx'),
('xgboost'),
('lightgbm'),
('nltk'),
('spacy'),
('langchain'),
('react'),
('angular'),
('vue'),
('next.js'),
('node.js'),
('express.js'),
('django'),
('flask'),
('fastapi'),
('spring'),
('spring boot'),
('laravel'),
('ruby on rails'),
('bootstrap'),
('tailwind css'),
('jquery'),
('asp.net'),
('mysql'),
('postgresql'),
('mongodb'),
('oracle'),
('sqlite'),
('redis'),
('mariadb'),
('microsoft sql server'),
('cassandra'),
('dynamodb'),
('firebase'),
('supabase'),
('neo4j'),
('aws'),
('microsoft azure'),
('google cloud'),
('docker'),
('kubernetes'),
('terraform'),
('amazon ec2'),
('amazon s3'),
('aws lambda'),
('git'),
('github'),
('gitlab'),
('bitbucket'),
('jenkins'),
('github actions'),
('ansible'),
('maven'),
('gradle'),
('npm'),
('yarn'),
('postman'),
('jira'),
('pandas'),
('numpy'),
('matplotlib'),
('seaborn'),
('plotly'),
('apache spark'),
('hadoop'),
('power bi'),
('tableau'),
('apache kafka'),
('databricks'),
('android studio'),
('flutter'),
('react native'),
('xcode'),
('swiftui'),
('jetpack compose'),
('cnn'),
('rnn'),
('lstm'),
('gru'),
('gan'),
('transformer'),
('bert'),
('gpt'),
('yolo'),
('resnet'),
('yolov5'),
('yolov8'),
('stable diffusion'),
('arduino'),
('raspberry pi'),
('esp32'),
('esp8266'),
('arduino ide'),
('matlab'),
('simulink'),
('verilog'),
('vhdl'),
('fpga'),
('labview'),
('autocad'),
('solidworks'),
('catia'),
('unity'),
('unreal engine'),
('blender'),
('figma'),
('apache'),
('nginx'),
('linux'),
('ubuntu'),
('virtualbox'),
('vmware'),
('elasticsearch'),
('logstash'),
('kibana'),
('grafana'),
('prometheus'),
('rabbitmq'),
('graphql'),
('rest api'),
('grpc'),
('websocket'),
('oauth'),
('jwt'),
('twilio'),
('stripe');


CREATE TABLE languages (
    language VARCHAR(100) NOT NULL UNIQUE
);

INSERT INTO languages (language) VALUES
('python'),
('java'),
('c'),
('c++'),
('c#'),
('javascript'),
('typescript'),
('go'),
('rust'),
('php'),
('ruby'),
('kotlin'),
('swift'),
('dart'),
('r'),
('matlab'),
('scala'),
('perl'),
('lua'),
('objective-c'),
('sql'),
('html'),
('css'),
('bash'),
('shell'),
('powershell'),
('assembly'),
('fortran'),
('cobol'),
('groovy'),
('haskell'),
('julia'),
('prolog'),
('erlang'),
('elixir'),
('f#'),
('visual basic'),
('vb.net'),
('delphi'),
('solidity'),
('verilog'),
('vhdl'),
('sas'),
('pl/sql');